2020-10-28 19:20:53,849 INFO: Demarrage de petits Gazouillis [in /home/etudiant/projetsPython/petits_gazouillis/app/__init__.py:50]
2020-10-28 22:08:33,413 INFO: Demarrage de petits Gazouillis [in /home/etudiant/projetsPython/petits_gazouillis/app/__init__.py:50]
2020-10-29 01:25:48,453 INFO: Demarrage de petits Gazouillis [in /home/etudiant/projetsPython/petits_gazouillis/app/__init__.py:50]
2020-10-29 06:11:45,300 INFO: Demarrage de petits Gazouillis [in /home/etudiant/projetsPython/petits_gazouillis/app/__init__.py:50]
2020-10-29 06:39:24,980 INFO: Demarrage de petits Gazouillis [in /home/etudiant/projetsPython/petits_gazouillis/app/__init__.py:50]
2020-10-29 06:48:31,967 INFO: Demarrage de petits Gazouillis [in /home/etudiant/projetsPython/petits_gazouillis/app/__init__.py:50]
2020-10-29 06:48:41,433 ERROR: Exception on /api/jeton [GET] [in /home/etudiant/projetsPython/petits_gazouillis/venv/lib/python3.7/site-packages/flask/app.py:1892]
Traceback (most recent call last):
  File "/home/etudiant/projetsPython/petits_gazouillis/venv/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/etudiant/projetsPython/petits_gazouillis/venv/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/etudiant/projetsPython/petits_gazouillis/venv/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/etudiant/projetsPython/petits_gazouillis/venv/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/etudiant/projetsPython/petits_gazouillis/venv/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/etudiant/projetsPython/petits_gazouillis/venv/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/etudiant/projetsPython/petits_gazouillis/venv/lib/python3.7/site-packages/flask_httpauth.py", line 163, in decorated
    return f(*args, **kwargs)
  File "/home/etudiant/projetsPython/petits_gazouillis/app/api/jeton.py", line 15, in get_jeton
    jeton = basic_auth.current_user().get_jeton()
  File "/home/etudiant/projetsPython/petits_gazouillis/app/modeles.py", line 108, in get_jeton
    self.jeton = base64.b64encode(os.urandom(24)).decode('utf-8')
NameError: name 'base64' is not defined
2020-10-29 06:50:45,641 INFO: Demarrage de petits Gazouillis [in /home/etudiant/projetsPython/petits_gazouillis/app/__init__.py:50]
2020-10-29 06:50:55,722 ERROR: Exception on /api/jeton [GET] [in /home/etudiant/projetsPython/petits_gazouillis/venv/lib/python3.7/site-packages/flask/app.py:1892]
Traceback (most recent call last):
  File "/home/etudiant/projetsPython/petits_gazouillis/venv/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/etudiant/projetsPython/petits_gazouillis/venv/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/etudiant/projetsPython/petits_gazouillis/venv/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/etudiant/projetsPython/petits_gazouillis/venv/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/etudiant/projetsPython/petits_gazouillis/venv/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/etudiant/projetsPython/petits_gazouillis/venv/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/etudiant/projetsPython/petits_gazouillis/venv/lib/python3.7/site-packages/flask_httpauth.py", line 163, in decorated
    return f(*args, **kwargs)
  File "/home/etudiant/projetsPython/petits_gazouillis/app/api/jeton.py", line 15, in get_jeton
    jeton = basic_auth.current_user().get_jeton()
  File "/home/etudiant/projetsPython/petits_gazouillis/app/modeles.py", line 110, in get_jeton
    self.jeton_expiration = maintenant + timedelta(seconds=expire_dans)
NameError: name 'timedelta' is not defined
2020-10-29 06:54:51,136 INFO: Demarrage de petits Gazouillis [in /home/etudiant/projetsPython/petits_gazouillis/app/__init__.py:50]
2020-10-29 06:55:02,432 ERROR: Exception on /api/publications [GET] [in /home/etudiant/projetsPython/petits_gazouillis/venv/lib/python3.7/site-packages/flask/app.py:1892]
Traceback (most recent call last):
  File "/home/etudiant/projetsPython/petits_gazouillis/venv/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/etudiant/projetsPython/petits_gazouillis/venv/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/etudiant/projetsPython/petits_gazouillis/venv/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/etudiant/projetsPython/petits_gazouillis/venv/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/etudiant/projetsPython/petits_gazouillis/venv/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/etudiant/projetsPython/petits_gazouillis/venv/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/etudiant/projetsPython/petits_gazouillis/venv/lib/python3.7/site-packages/flask_httpauth.py", line 163, in decorated
    return f(*args, **kwargs)
  File "/home/etudiant/projetsPython/petits_gazouillis/app/api/publications.py", line 25, in get_publications
    data = Publication.to_collection_dict(Publication.query, page, par_page, 'api.get_publications')
  File "/home/etudiant/projetsPython/petits_gazouillis/app/modeles.py", line 24, in to_collection_dict
    'items': [item.to_dict() for item in ressources.items],
  File "/home/etudiant/projetsPython/petits_gazouillis/app/modeles.py", line 24, in <listcomp>
    'items': [item.to_dict() for item in ressources.items],
  File "/home/etudiant/projetsPython/petits_gazouillis/app/modeles.py", line 140, in to_dict
    return data
UnboundLocalError: local variable 'data' referenced before assignment
2020-10-29 06:56:53,036 INFO: Demarrage de petits Gazouillis [in /home/etudiant/projetsPython/petits_gazouillis/app/__init__.py:50]
2020-10-29 06:57:04,946 ERROR: Exception on /api/publications [GET] [in /home/etudiant/projetsPython/petits_gazouillis/venv/lib/python3.7/site-packages/flask/app.py:1892]
Traceback (most recent call last):
  File "/home/etudiant/projetsPython/petits_gazouillis/venv/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/etudiant/projetsPython/petits_gazouillis/venv/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/etudiant/projetsPython/petits_gazouillis/venv/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/etudiant/projetsPython/petits_gazouillis/venv/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/etudiant/projetsPython/petits_gazouillis/venv/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/etudiant/projetsPython/petits_gazouillis/venv/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/etudiant/projetsPython/petits_gazouillis/venv/lib/python3.7/site-packages/flask_httpauth.py", line 163, in decorated
    return f(*args, **kwargs)
  File "/home/etudiant/projetsPython/petits_gazouillis/app/api/publications.py", line 25, in get_publications
    data = Publication.to_collection_dict(Publication.query, page, par_page, 'api.get_publications')
  File "/home/etudiant/projetsPython/petits_gazouillis/app/modeles.py", line 24, in to_collection_dict
    'items': [item.to_dict() for item in ressources.items],
  File "/home/etudiant/projetsPython/petits_gazouillis/app/modeles.py", line 24, in <listcomp>
    'items': [item.to_dict() for item in ressources.items],
  File "/home/etudiant/projetsPython/petits_gazouillis/app/modeles.py", line 140, in to_dict
    return data
UnboundLocalError: local variable 'data' referenced before assignment
2020-10-29 06:58:28,732 INFO: Demarrage de petits Gazouillis [in /home/etudiant/projetsPython/petits_gazouillis/app/__init__.py:50]
2020-10-29 06:58:35,934 INFO: Demarrage de petits Gazouillis [in /home/etudiant/projetsPython/petits_gazouillis/app/__init__.py:50]
2020-10-29 06:59:08,708 INFO: Demarrage de petits Gazouillis [in /home/etudiant/projetsPython/petits_gazouillis/app/__init__.py:50]
2020-10-29 07:00:29,182 INFO: Demarrage de petits Gazouillis [in /home/etudiant/projetsPython/petits_gazouillis/app/__init__.py:50]
2020-10-29 07:17:02,018 INFO: Demarrage de petits Gazouillis [in /home/etudiant/projetsPython/petits_gazouillis/app/__init__.py:50]
2020-10-29 07:21:20,389 INFO: Demarrage de petits Gazouillis [in /home/etudiant/projetsPython/petits_gazouillis/app/__init__.py:50]
2020-10-29 07:28:12,591 INFO: Demarrage de petits Gazouillis [in /home/etudiant/projetsPython/petits_gazouillis/app/__init__.py:50]
2020-10-29 07:30:53,371 INFO: Demarrage de petits Gazouillis [in /home/etudiant/projetsPython/petits_gazouillis/app/__init__.py:50]
2020-10-29 09:03:59,616 INFO: Demarrage de petits Gazouillis [in /home/etudiant/projetsPython/petits_gazouillis/app/__init__.py:50]
2020-10-29 10:19:13,961 INFO: Demarrage de petits Gazouillis [in /home/etudiant/projetsPython/petits_gazouillis/app/__init__.py:50]
